# Generated by Django 3.1.2 on 2020-11-20 14:04

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=56, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Plantila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=126, upload_to='Plantillas/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=56)),
                ('apellido_paterno', models.CharField(max_length=56)),
                ('apellido_materno', models.CharField(max_length=56)),
                ('email_institucional', models.CharField(max_length=126, validators=[django.core.validators.RegexValidator(message='El formato del correo debe ser @tectijuana.edu.mx', regex='(^[a-zA-Z0-9_.+-]+@tectijuana.edu.mx+$)')])),
                ('foto', models.ImageField(blank=True, max_length=126, null=True, upload_to=core.models.rename_folder_photo)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modulo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=56)),
                ('nombre', models.CharField(max_length=56)),
                ('apellido_paterno', models.CharField(max_length=56)),
                ('apellido_materno', models.CharField(max_length=56)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio', models.FileField(blank=True, max_length=126, null=True, upload_to=core.models.rename_folder_credito)),
                ('nombre', models.CharField(blank=True, max_length=126, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expediente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
            },
        ),
    ]
