# Generated by Django 3.1.2 on 2020-11-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plantila',
        ),
    ]
