# Generated by Django 3.1.2 on 2020-11-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_plantila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=126, upload_to='Plantillas/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
            },
        ),
    ]
