# Generated by Django 3.1.2 on 2020-11-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plantila'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantila',
            new_name='Plantilla',
        ),
    ]
