# Generated by Django 3.1.2 on 2020-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plantilla_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Redaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=56)),
                ('nombre', models.CharField(max_length=56)),
                ('carrera', models.CharField(max_length=56)),
                ('jefa', models.CharField(max_length=56)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
            ],
            options={
                'verbose_name_plural': 'Historial de Redaccion',
            },
        ),
    ]
