# Generated by Django 3.1.2 on 2020-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historial_redaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_redaccion',
            name='carrera',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='historial_redaccion',
            name='jefa',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='historial_redaccion',
            name='nombre',
            field=models.CharField(max_length=126),
        ),
    ]
