# Generated by Django 3.1.2 on 2020-12-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_modulo_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_redaccion',
            name='valor',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
