# Generated by Django 3.1.2 on 2020-12-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historial_redaccion_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_redaccion',
            name='modulo',
            field=models.CharField(default=1, max_length=126),
            preserve_default=False,
        ),
    ]
