# Generated by Django 3.1.2 on 2021-01-02 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20210102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
