# Generated by Django 3.1.2 on 2021-01-03 16:46

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20210102_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=56)),
                ('nombre', models.CharField(max_length=56)),
                ('apellido_paterno', models.CharField(max_length=56)),
                ('apellido_materno', models.CharField(max_length=56)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil')),
            ],
            options={
                'verbose_name': 'Expediente de Servicio',
                'verbose_name_plural': 'Expedientes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Documento_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio', models.FileField(blank=True, max_length=126, null=True, upload_to=core.models.rename_folder_credito)),
                ('nombre', models.CharField(blank=True, max_length=126, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado ')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expediente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Servicio',
                'verbose_name_plural': 'Documentos de Servicio',
            },
        ),
    ]
