# Generated by Django 3.1.2 on 2021-01-03 18:23

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documento_servicio_expediente_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento_servicio',
            name='directorio',
            field=models.FileField(blank=True, max_length=126, null=True, upload_to=core.models.rename_folder_documento),
        ),
        migrations.AlterField(
            model_name='documento_servicio',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expediente_servicio'),
        ),
    ]
